services:
  web:
    build: .
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./src/backend/laravel-crud-api:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: splus_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: splus_db
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: php_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db